### ISSUE TITLE
Fix markdown parsing of results

### ISSUE THREAD

**Issue by tommysteryy** [xoo-creative/flash#47]
## Description
A few common problems arise when generating content to show the user.

Since we generate a `page` with `taipy.gui.Markdown`, it needs to pass their strict parsing rules. So far, I have run into problems like:
- `An Error occurred: SyntaxError: Unexpected token `}`. Did you mean `&rbrace;` or `{"}"}`? (202:108)`
- Parsing error of "HTML Tag is unclosed on <T>"
- Parsing error of unicode decoding something

This is preventing the service from being fully reliable since sometimes the markdown is valid, sometimes not.

## Acceptance Criteria
Remove the problem of inconsistent markdown pages, and every time we generate, it always works.

## Tasks
- [ ] Look for better markdown linters?
- [ ] Explore using an agent to check the markdown
- [ ] Explore more manual adjustments that I can make
