### ISSUE TITLE
Move AsyncAgent functionality to Lambda Function

### ISSUE THREAD

**Issue by tommysteryy** [xoo-creative/flash#57]
## Description
Currently, there is no way to use an async function as a callback to a button on `taipy.Gui`. The alternative is to set up an entire `Scenario` and `Pipeline` through `taipy`, but the concept of "scenario` doesn't really suit our use case in flash.

Therefore, it would make more sense to move all `Agent` things to a Lambda which we invoke once, in our `generate` function. This lambda would basically consist of our `AsyncAgent` and complete all calls there.

## Acceptance Criteria
A working Lambda function which we can call from the `taipy` app.

## Tasks
- [x] Find good lambda template repo in python
- [x] Test out manually with `Postman`
- [ ] Test out in `taipy`

**Comment by tommysteryy** [comment]
The lambda is now deployed, and its code lives in [flash-agent](https://github.com/xoo-creative/flash-agent).

All we need to do now is to run and test the invocation from flash.
